import type { Metadata } from "next";
import { Roboto } from "next/font/google";  // Roboto fontunu import ediyoruz
import "./globals.css";

// Roboto fontunu yapılandırıyoruz
const roboto = Roboto({
    weight: "400",  // İstediğiniz font ağırlığını belirtebilirsiniz
    subsets: ["latin"],  // Latin karakter seti
    variable: "--font-roboto",  // CSS değişkeni olarak kullanılacak ad
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${roboto.variable} antialiased`}>  {/* Roboto fontunu sınıf olarak ekliyoruz */}
        {children}
        </body>
        </html>
    );
}
