import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import theme from "./themes/theme";
import {ThemeProvider} from "@mui/material/styles";
import { CssBaseline } from '@mui/material/';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props : { children: React.ReactNode; }) {

  return (
      <html lang="en">
      <body>
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
            <CssBaseline/>
          {props.children}
        </ThemeProvider>
      </AppRouterCacheProvider>
      </body>
      </html>
  );
}
//slider --> içinde image ler var
//slider hazırlandı, slider bir component, image de bir component
//slider componentinin içine image i childiren olaran koydum
//özetle bir sliderım var, içine childerin koyacak şekilde ayarlıyorum


